export default {
    LIMPAR_FILTROS_BUSCA_LICITACAO: 'limparFiltrosBuscaLicitacao',
    LOKI: {
        DISABLE_GLOBAL_LOADING: 'disableGlobalLoading',
        ENABLE_GLOBAL_LOADING: 'enableGlobalLoading',
        SET_GLOBAL_LOADING: 'setGlobalLoading',
        SET_LOADING_MESSAGE: 'setLoadingMessage',
        SET_TIMEZONE: 'setTimezone'
    },
    MOSTRAR_MENSAGEM_ERRO: 'mostrarMensagemErro',
    MOSTRAR_MENSAGEM_ERRO_DEFAULT: 'mostrarMensagemErroDefault',
    MOSTRAR_MENSAGEM_ERRO_PERDA_SESSAO: 'mostrarMensagemErroPerdaSessao',
    MOSTRAR_MENSAGEM_SUCESSO_DEFAULT: 'mostrarMensagemSucessoDefault',
    SET_ANEXOS_LICITACAO: 'setAnexosLicitacao',
    SET_COMISSAO: 'setComissao',
    SET_FILTROS_BUSCA_COMISSAO: 'setFiltrosBuscaComissao',
    SET_FILTROS_BUSCA_LICITACAO: 'setFiltrosBuscaLicitacao',
    SET_FILTROS_BUSCA_USUARIO: 'setFiltrosBuscaUsuario',
    SET_FORNECEDOR_ACEITE: 'setFornecedorAceite',
    SET_LICITACAO: 'setLicitacao',
    SET_LOTES_LICITACAO: 'setLotesLicitacao',
    SET_MENU_AVATAR: 'setMenuAvatar',
    SET_ORGAOS: 'setOrgaos',
    SET_PAGINACAO_BUSCA_LICITACAO: 'setPaginacaoBuscaLicitacao',
    SET_PAGINACAO_BUSCA_LICITACOES_FAVORITAS_FORNECEDOR: 'setPaginacaoBuscaLicitacoesFavoritasFornecedor',
    SET_PAGINACAO_BUSCA_LICITACOES_COM_PROPOSTA_FORNECEDOR: 'setPaginacaoBuscaLicitacoesComPropostaFornecedor',
    SET_PERFIS: 'setPerfis',
    SET_PRODUTO: 'setProduto',
    SET_PROPOSTA_RESUMO: 'setPropostaResumo',
    SET_TERMO_ACEITE_PROPOSTA: 'setTermoAceiteProposta',
    SET_USUARIO: 'setUsuario',
    SET_USUARIO_LOGADO: 'setUsuarioLogado'
}
